name: Code Quality Checks
on: [push]

jobs:

  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install Dependencies
      run: npm install

    - name: Check Dependencies Vulnerabilities
      run: npm audit

  quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install Dependencies
      run: npm install

    - name: Formatting
      run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install Dependencies
      run: npm install

    - name: Jest
      run: npm test
